### ISSUE TITLE
Error when running the command in jupyter notebook

### ISSUE THREAD

**Issue by sallyqus** [wukevin/babel#2]
Hi Kevin, thanks for the great work.

I encountered several problems in the environment based on the yml file you provided. It may help others who wanna follow your work if you can double check like scipy and tensorboard versions. It reported conflicts for the packages when building the env using the yml. After uninstalling and installing those, their versions in my workstation that work for BABEL are different from yours.

And the jupyter notebook seems to be not runnable? This is the command I used: 
`python bin/predict_model.py --checkpoint /home/qus/SallyProjects/sc-GAT/babel/cv_logsplit_01_model_only --data data/atac_v1_pbmc_10k_filtered_peak_bc_matrix.h5 --outdir babel_atac_to_rna_pbmc --noplot --liftHg19toHg38 --transonly --device 0`

When I run the command I got the error:
```
WARNING:root:Found unmapped regions: 48
INFO:root:Read in data/atac_v1_pbmc_10k_filtered_peak_bc_matrix.h5 for (8633, 223897) (obs x var)
Traceback (most recent call last):
  File "/home/qus/anaconda3/lib/python3.7/site-packages/pandas/core/indexes/base.py", line 2895, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 70, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 101, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 1675, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 1683, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'n_counts'

```
Then, without a doubt, I cannot run the notebook. According to your readme.txt, its due to you only provide one .h5 file to the command? I am not sure... Or anything I did it wrongly? Could you help to fix this? Thanks in advance!! For sure, your paper will be cited in our submission.

PS: I agree with the previous issue that more detailed examples to reproduce results on datasets (both paired and unpaired) more easily could be very helpful. :)

**Comment by sallyqus** [comment]
This is because that in function `annotate_basic_adata_metrics`, adata.obs is DataFrameView while adata.var is DataFrame. So `adata.**obs**['n_counts'] = np.squeeze(np.asarray((adata.X.sum(1))))` is not working. The difference comes from `obs=self.data_raw.obs, var=pd.DataFrame(index=names)` in function _pool_feature in sc_data_loader.py. 

It can be solved by inserting a line `adata.obs = pd.DataFrame(adata.obs) ` before `adata.obs['n_counts'] = np.squeeze(np.asarray((adata.X.sum(1))))` in adata_utils.py.

**Comment by wukevin** [comment]
This is quite strange – I just did totally clean installation of the conda environment, and was not able to reproduce the error that you're seeing. Can you please post the full results of doing `conda list` while the `babel` environment is active? Perhaps that will help us track down the exact issue.

For reference, here's my output of `conda list`
```
# packages in environment at /home/wukevin/miniconda3/envs/babel:
#
# Name                    Version                   Build  Channel
absl-py                   0.10.0                   py37_0    anaconda
adjusttext                0.7.3.1                    py_1    conda-forge
anndata                   0.6.22.post1               py_0    bioconda
argon2-cffi               20.1.0           py37h7b6447c_1    anaconda
astropy                   4.0.1.post1      py37h8f50634_0    conda-forge
async_generator           1.10             py37h28b3542_0    anaconda
attrs                     20.2.0                     py_0    anaconda
backcall                  0.2.0                      py_0    anaconda
blas                      1.0                         mkl    anaconda
bleach                    3.2.1                      py_0    anaconda
blosc                     1.19.0               hd408876_0    anaconda
bzip2                     1.0.8                h7b6447c_0    anaconda
c-ares                    1.16.1               h7b6447c_0    anaconda
ca-certificates           2020.10.14                    0    anaconda
cached-property           1.5.2                      py_0    anaconda
cairo                     1.14.12              h8948797_3    anaconda
captum                    0.2.0                         0    pytorch
certifi                   2020.6.20                py37_0    anaconda
cffi                      1.14.3           py37he30daa8_0    anaconda
cudatoolkit               10.1.243             h6bb024c_0    anaconda
cycler                    0.10.0                   py37_0    anaconda
dbus                      1.13.18              hb2f20db_0    anaconda
decorator                 4.4.2                      py_0    anaconda
defusedxml                0.6.0                      py_0    anaconda
entrypoints               0.3                      py37_0    anaconda
expat                     2.2.10               he6710b0_2    anaconda
fast-histogram            0.9              py37heb32a55_0    anaconda
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.4               h5ab3b9f_0    anaconda
glib                      2.56.2               hd408876_0    anaconda
gmp                       6.1.2                hb3b607b_0    anaconda
grpcio                    1.31.0           py37hf8bcb03_0    anaconda
gst-plugins-base          1.14.0               hbbd80ab_1    anaconda
gstreamer                 1.14.0               hb453b48_1    anaconda
h5py                      2.10.0           py37h7918eee_0    anaconda
hdf5                      1.10.4               hb1b8bf9_0    anaconda
icu                       58.2                 he6710b0_3    anaconda
igraph                    0.7.1             h2166141_1005    conda-forge
importlib-metadata        2.0.0                      py_1    anaconda
importlib_metadata        2.0.0                         1    anaconda
intel-openmp              2020.2                      254    anaconda
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.3.4            py37h5ca1d4c_0    anaconda
ipython                   7.18.1           py37h5ca1d4c_0    anaconda
ipython_genutils          0.2.0                    py37_0    anaconda
ipywidgets                7.5.1                      py_1    anaconda
jedi                      0.17.2                   py37_0    anaconda
jinja2                    2.11.2                     py_0    anaconda
joblib                    0.17.0                     py_0    anaconda
jpeg                      9b                   habf39ab_1    anaconda
jsonschema                3.2.0                      py_2    anaconda
jupyter                   1.0.0            py37h89c1867_6    conda-forge
jupyter_client            6.1.7                      py_0    anaconda
jupyter_console           6.2.0                      py_0    anaconda
jupyter_core              4.6.3                    py37_0    anaconda
jupyterlab_pygments       0.1.2                      py_0    anaconda
kiwisolver                1.2.0            py37hfd86e86_0    anaconda
lcms2                     2.11                 h396b838_0    anaconda
ld_impl_linux-64          2.33.1               h53a641e_7    anaconda
leidenalg                 0.7.0            py37h3340039_2    conda-forge
libedit                   3.1.20191231         h14c3975_1    anaconda
libffi                    3.3                  he6710b0_2    anaconda
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libiconv                  1.15                 h63c8f33_5    anaconda
libllvm10                 10.0.1               hbcb73fb_5    anaconda
libpng                    1.6.37               hbc83047_0    anaconda
libprotobuf               3.13.0.1             hd408876_0    anaconda
libsodium                 1.0.18               h7b6447c_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libtiff                   4.1.0                h2733197_1    anaconda
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.14                 h7b6447c_0    anaconda
libxml2                   2.9.10               hb55368b_3    anaconda
llvmlite                  0.34.0           py37h269e1b5_4    anaconda
louvain                   0.6.1            py37he1b5a44_2    conda-forge
lz4-c                     1.9.2                heb0550a_3    anaconda
lzo                       2.10                 h7b6447c_2    anaconda
markdown                  3.3.2                    py37_0    anaconda
markupsafe                1.1.1            py37h14c3975_1    anaconda
matplotlib                3.3.1                         0    anaconda
matplotlib-base           3.3.1            py37h817c723_0    anaconda
mistune                   0.8.4           py37h14c3975_1001    anaconda
mkl                       2019.4                      243    anaconda
mkl-service               2.3.0            py37he904b0f_0    anaconda
mkl_fft                   1.2.0            py37h23d657b_0    anaconda
mkl_random                1.1.0            py37hd6b4f25_0    anaconda
mock                      4.0.2                      py_0    anaconda
mpl-scatter-density       0.7                        py_0    conda-forge
mysql-connector-c         6.1.11               h597af5e_1    anaconda
natsort                   7.0.1                      py_0    anaconda
nbclient                  0.5.1                      py_0    anaconda
nbconvert                 6.0.7                    py37_0    anaconda
nbformat                  5.0.8                      py_0    anaconda
ncurses                   6.2                  he6710b0_1    anaconda
nest-asyncio              1.4.1                      py_0    anaconda
networkx                  2.5                        py_0    anaconda
ninja                     1.10.1           py37hfd86e86_0    anaconda
notebook                  6.1.4                    py37_0    anaconda
numba                     0.51.2           py37h04863e7_1    anaconda
numexpr                   2.7.1            py37h423224d_0    anaconda
numpy                     1.17.4           py37hc1035e2_0    anaconda
numpy-base                1.17.4           py37hde5b4d6_0    anaconda
olefile                   0.46                     py37_0    anaconda
openssl                   1.1.1h               h7b6447c_0    anaconda
packaging                 20.4                       py_0    anaconda
pandas                    0.25.3           py37he6710b0_0    anaconda
pandoc                    2.11                 hb0f4dca_0    anaconda
pandocfilters             1.4.2                    py37_1    anaconda
parso                     0.7.0                      py_0    anaconda
patsy                     0.5.1                    py37_0    anaconda
pcre                      8.44                 he6710b0_0    anaconda
pexpect                   4.8.0                    py37_1    anaconda
pickleshare               0.7.5                 py37_1001    anaconda
pillow                    8.0.0            py37h9a89aac_0    anaconda
pip                       20.2.4                   py37_0    anaconda
pixman                    0.40.0               h7b6447c_0    anaconda
prometheus_client         0.8.0                      py_0    anaconda
prompt-toolkit            3.0.8                      py_0    anaconda
prompt_toolkit            3.0.8                         0    anaconda
protobuf                  3.13.0.1         py37he6710b0_1    anaconda
ptyprocess                0.6.0                    py37_0    anaconda
pycairo                   1.19.1           py37h2a1e443_0    anaconda
pycparser                 2.20                       py_2    anaconda
pygments                  2.7.1                      py_0    anaconda
pyparsing                 2.4.7                      py_0    anaconda
pyqt                      5.9.2            py37h22d08a2_1    anaconda
pyrsistent                0.17.3           py37h7b6447c_0    anaconda
pytables                  3.6.1            py37h71ec239_0    anaconda
python                    3.7.9                h7579374_0    anaconda
python-dateutil           2.8.1                      py_0    anaconda
python-igraph             0.7.1.post7      py37h516909a_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2020.1                     py_0    anaconda
pyzmq                     19.0.2           py37he6710b0_1    anaconda
qt                        5.9.7                h5867ecd_1    anaconda
qtconsole                 4.7.7                      py_0    anaconda
qtpy                      1.9.0                      py_0    anaconda
readline                  8.0                  h7b6447c_0    anaconda
scanpy                    1.4.4.post1                py_0    bioconda
scikit-learn              0.21.3           py37hd81dba3_0    anaconda
scipy                     1.3.2            py37h7c811a0_0    anaconda
seaborn                   0.11.0                     py_0    anaconda
send2trash                1.5.0                    py37_0    anaconda
setuptools                50.3.0           py37hb0f4dca_1    anaconda
sip                       4.19.24          py37he6710b0_0    anaconda
six                       1.15.0                     py_0    anaconda
skorch                    0.7.0              pyh5ca1d4c_0    conda-forge
snappy                    1.1.8                he6710b0_0    anaconda
sortedcontainers          2.2.2                      py_0    anaconda
sqlite                    3.33.0               h62c20be_0    anaconda
statsmodels               0.10.1           py37hdd07704_0    anaconda
tabulate                  0.8.7                    py37_0    anaconda
tbb                       2020.3               hfd86e86_0    anaconda
tensorboard               2.0.0              pyhb38c66f_1    anaconda
terminado                 0.9.1                    py37_0    anaconda
testpath                  0.4.4                      py_0    anaconda
tk                        8.6.10               hbc83047_0    anaconda
torchvision               0.4.2                py37_cu101    pytorch
tornado                   6.0.4            py37h7b6447c_1    anaconda
tqdm                      4.50.2                     py_0    anaconda
traitlets                 5.0.5                      py_0    anaconda
ucsc-liftover             357                  h446ed27_4    bioconda
umap-learn                0.4.6            py37hc8dfbb8_0    conda-forge
wcwidth                   0.2.5                      py_0    anaconda
webencodings              0.5.1                    py37_1    anaconda
werkzeug                  1.0.1                      py_0    anaconda
wheel                     0.35.1                     py_0    anaconda
widgetsnbextension        3.5.1                    py37_0    anaconda
xz                        5.2.5                h7b6447c_0    anaconda
zeromq                    4.3.3                he6710b0_3    anaconda
zipp                      3.3.1                      py_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.4.4                h0b5b093_3    anaconda
```

**Comment by sallyqus** [comment]
Hi thanks for your response!!

It is truly quite weird. Since I ecountered the llvmlite package problem..I gave up the first env built for babel. It is because I have llvmlite 0.28.0 installed before in my base env and this annoying package needs to be removed from base env first otherwise it will report an installation error since it always shows the old one 0.28.0 in my base env when `pip list` in babel env.

Anyway, to avoid any env difference, I built **babel2** env for babel from scratch. The installation is ok but it is not runnable.... with neither 
`python bin/train_model.py --shareseq 'skin' --outdir share_model`
nor 
`python bin/train_model.py --snareseq --outdir snare_model `.

It first reported the scanpy version problem saying scanpy.preprocessing does not have attribute `normalize_total.` When I check in python console, it has `normalize_per_cell` instead... WEIRD.. So I installed the 1.4.6 version. Then it worked for a while and reported another error as follows:

For snareseq:
```
INFO:root:Checking obs names for two input datasets
/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/anndata/_core/anndata.py:1229: ImplicitModificationWarning: Initializing view as actual.
  "Initializing view as actual.", ImplicitModificationWarning
Trying to set attribute `.var` of view, copying.
... storing 'chrom' as categorical
INFO:root:ChromDecoder with 1 output activations
Traceback (most recent call last):
  File "bin/train_model.py", line 554, in <module>
    main()
  File "bin/train_model.py", line 464, in main
    spliced_net.fit(sc_dual_train_dataset, y=None)
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/skorch/net.py", line 848, in fit
    self.partial_fit(X, y, **fit_params)
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/skorch/net.py", line 807, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/skorch/net.py", line 735, in fit_loop
    for data in self.get_iterator(dataset_train, training=True):
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qus/SallyProjects/sc-GAT/babel/babel/sc_data_loaders.py", line 1019, in __getitem__
    x1 = self.dataset_x[i]
  File "/home/qus/SallyProjects/sc-GAT/babel/babel/sc_data_loaders.py", line 838, in __getitem__
    return self.dset.get_item_data_split(index, self.split)
  File "/home/qus/SallyProjects/sc-GAT/babel/babel/sc_data_loaders.py", line 667, in get_item_data_split
    return self.__getitem__(self.data_split_to_idx[split][idx])
  File "/home/qus/SallyProjects/sc-GAT/babel/babel/sc_data_loaders.py", line 695, in __getitem__
    target = torch.from_numpy(self.size_norm_counts.var_vector(y_idx)).type(
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/anndata/_core/anndata.py", line 1417, in var_vector
    return get_vector(self, k, "var", "obs", layer=layer)
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/anndata/_core/index.py", line 180, in get_vector
    f"Could not find key {k} in .{idxdim}_names or .{coldim}.columns."
KeyError: 'Could not find key 2977 in .obs_names or .var.columns.'
```

For shareseq:
```
/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/anndata/_core/anndata.py:1229: ImplicitModificationWarning: Initializing view as actual.
  "Initializing view as actual.", ImplicitModificationWarning
Trying to set attribute `.var` of view, copying.
... storing 'chrom' as categorical
INFO:root:ChromDecoder with 1 output activations
Traceback (most recent call last):
  File "bin/train_model.py", line 554, in <module>
    main()
  File "bin/train_model.py", line 464, in main
    spliced_net.fit(sc_dual_train_dataset, y=None)
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/skorch/net.py", line 848, in fit
    self.partial_fit(X, y, **fit_params)
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/skorch/net.py", line 807, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/skorch/net.py", line 735, in fit_loop
    for data in self.get_iterator(dataset_train, training=True):
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/qus/SallyProjects/sc-GAT/babel/babel/sc_data_loaders.py", line 1019, in __getitem__
    x1 = self.dataset_x[i]
  File "/home/qus/SallyProjects/sc-GAT/babel/babel/sc_data_loaders.py", line 838, in __getitem__
    return self.dset.get_item_data_split(index, self.split)
  File "/home/qus/SallyProjects/sc-GAT/babel/babel/sc_data_loaders.py", line 667, in get_item_data_split
    return self.__getitem__(self.data_split_to_idx[split][idx])
  File "/home/qus/SallyProjects/sc-GAT/babel/babel/sc_data_loaders.py", line 695, in __getitem__
    target = torch.from_numpy(self.size_norm_counts.var_vector(y_idx)).type(
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/anndata/_core/anndata.py", line 1417, in var_vector
    return get_vector(self, k, "var", "obs", layer=layer)
  File "/home/qus/anaconda3/envs/babel2/lib/python3.7/site-packages/anndata/_core/index.py", line 180, in get_vector
    f"Could not find key {k} in .{idxdim}_names or .{coldim}.columns."
KeyError: 'Could not find key 22628 in .obs_names or .var.columns.'
```

This should not be a package/env problem. Do you have the same errors if you run the commands I mentioned for snareseq and shareseq? 

Here is my conda list:
```
^^>>> conda list                                                                                                                             (babel2) 09:57:56 
# packages in environment at /home/qus/anaconda3/envs/babel2:
#
# Name                    Version                   Build  Channel
absl-py                   0.10.0                   py37_0    anaconda
adjusttext                0.7.3.1                    py_1    conda-forge
anndata                   0.7.6                    pypi_0    pypi
argon2-cffi               20.1.0           py37h7b6447c_1    anaconda
astropy                   4.0.1.post1      py37h8f50634_0    conda-forge
async_generator           1.10             py37h28b3542_0    anaconda
attrs                     20.2.0                     py_0    anaconda
backcall                  0.2.0                      py_0    anaconda
blas                      1.0                         mkl    anaconda
bleach                    3.2.1                      py_0    anaconda
blosc                     1.19.0               hd408876_0    anaconda
bzip2                     1.0.8                h7b6447c_0    anaconda
c-ares                    1.16.1               h7b6447c_0    anaconda
ca-certificates           2020.10.14                    0    anaconda
cached-property           1.5.2                      py_0    anaconda
cairo                     1.14.12              h8948797_3    anaconda
captum                    0.2.0                         0    pytorch
certifi                   2020.6.20                py37_0    anaconda
cffi                      1.14.3           py37he30daa8_0    anaconda
cudatoolkit               10.1.243             h6bb024c_0    anaconda
cycler                    0.10.0                   py37_0    anaconda
dbus                      1.13.18              hb2f20db_0    anaconda
decorator                 4.4.2                      py_0    anaconda
defusedxml                0.6.0                      py_0    anaconda
entrypoints               0.3                      py37_0    anaconda
expat                     2.2.10               he6710b0_2    anaconda
fast-histogram            0.9              py37heb32a55_0    anaconda
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.4               h5ab3b9f_0    anaconda
get-version               2.1                      pypi_0    pypi
glib                      2.56.2               hd408876_0    anaconda
gmp                       6.1.2                hb3b607b_0    anaconda
grpcio                    1.31.0           py37hf8bcb03_0    anaconda
gst-plugins-base          1.14.0               hbbd80ab_1    anaconda
gstreamer                 1.14.0               hb453b48_1    anaconda
h5py                      2.10.0           py37h7918eee_0    anaconda
hdf5                      1.10.4               hb1b8bf9_0    anaconda
icu                       58.2                 he6710b0_3    anaconda
igraph                    0.7.1             h2166141_1005    conda-forge
importlib-metadata        2.0.0                      py_1    anaconda
importlib_metadata        2.0.0                         1    anaconda
intel-openmp              2020.2                      254    anaconda
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.3.4            py37h5ca1d4c_0    anaconda
ipython                   7.18.1           py37h5ca1d4c_0    anaconda
ipython_genutils          0.2.0                    py37_0    anaconda
ipywidgets                7.5.1                      py_1    anaconda
jedi                      0.17.2                   py37_0    anaconda
jinja2                    2.11.2                     py_0    anaconda
joblib                    0.17.0                     py_0    anaconda
jpeg                      9b                   habf39ab_1    anaconda
jsonschema                3.2.0                      py_2    anaconda
jupyter                   1.0.0            py37h89c1867_6    conda-forge
jupyter_client            6.1.7                      py_0    anaconda
jupyter_console           6.2.0                      py_0    anaconda
jupyter_core              4.6.3                    py37_0    anaconda
jupyterlab_pygments       0.1.2                      py_0    anaconda
kiwisolver                1.2.0            py37hfd86e86_0    anaconda
lcms2                     2.11                 h396b838_0    anaconda
ld_impl_linux-64          2.33.1               h53a641e_7    anaconda
legacy-api-wrap           1.2                      pypi_0    pypi
leidenalg                 0.7.0            py37h3340039_2    conda-forge
libedit                   3.1.20191231         h14c3975_1    anaconda
libffi                    3.3                  he6710b0_2    anaconda
libgcc-ng                 9.1.0                hdf63c60_0    anaconda
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libiconv                  1.15                 h63c8f33_5    anaconda
libllvm10                 10.0.1               hbcb73fb_5    anaconda
libpng                    1.6.37               hbc83047_0    anaconda
libprotobuf               3.13.0.1             hd408876_0    anaconda
libsodium                 1.0.18               h7b6447c_0    anaconda
libstdcxx-ng              9.1.0                hdf63c60_0    anaconda
libtiff                   4.1.0                h2733197_1    anaconda
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.14                 h7b6447c_0    anaconda
libxml2                   2.9.10               hb55368b_3    anaconda
llvmlite                  0.34.0           py37h269e1b5_4    anaconda
louvain                   0.6.1            py37he1b5a44_2    conda-forge
lz4-c                     1.9.2                heb0550a_3    anaconda
lzo                       2.10                 h7b6447c_2    anaconda
markdown                  3.3.2                    py37_0    anaconda
markupsafe                1.1.1            py37h14c3975_1    anaconda
matplotlib                3.3.1                         0    anaconda
matplotlib-base           3.3.1            py37h817c723_0    anaconda
mistune                   0.8.4           py37h14c3975_1001    anaconda
mkl                       2019.4                      243    anaconda
mkl-service               2.3.0            py37he904b0f_0    anaconda
mkl_fft                   1.2.0            py37h23d657b_0    anaconda
mkl_random                1.1.0            py37hd6b4f25_0    anaconda
mock                      4.0.2                      py_0    anaconda
mpl-scatter-density       0.7                        py_0    conda-forge
mysql-connector-c         6.1.11               h597af5e_1    anaconda
natsort                   7.0.1                      py_0    anaconda
nbclient                  0.5.1                      py_0    anaconda
nbconvert                 6.0.7                    py37_0    anaconda
nbformat                  5.0.8                      py_0    anaconda
ncurses                   6.2                  he6710b0_1    anaconda
nest-asyncio              1.4.1                      py_0    anaconda
networkx                  2.5                        py_0    anaconda
ninja                     1.10.1           py37hfd86e86_0    anaconda
notebook                  6.1.4                    py37_0    anaconda
numba                     0.51.2           py37h04863e7_1    anaconda
numexpr                   2.7.1            py37h423224d_0    anaconda
numpy                     1.17.4           py37hc1035e2_0    anaconda
numpy-base                1.17.4           py37hde5b4d6_0    anaconda
olefile                   0.46                     py37_0    anaconda
openssl                   1.1.1h               h7b6447c_0    anaconda
packaging                 20.4                       py_0    anaconda
pandas                    0.25.3           py37he6710b0_0    anaconda
pandoc                    2.11                 hb0f4dca_0    anaconda
pandocfilters             1.4.2                    py37_1    anaconda
parso                     0.7.0                      py_0    anaconda
patsy                     0.5.1                    py37_0    anaconda
pcre                      8.44                 he6710b0_0    anaconda
pexpect                   4.8.0                    py37_1    anaconda
pickleshare               0.7.5                 py37_1001    anaconda
pillow                    8.0.0            py37h9a89aac_0    anaconda
pip                       20.2.4                   py37_0    anaconda
pixman                    0.40.0               h7b6447c_0    anaconda
prometheus_client         0.8.0                      py_0    anaconda
prompt-toolkit            3.0.8                      py_0    anaconda
prompt_toolkit            3.0.8                         0    anaconda
protobuf                  3.13.0.1         py37he6710b0_1    anaconda
ptyprocess                0.6.0                    py37_0    anaconda
pycairo                   1.19.1           py37h2a1e443_0    anaconda
pycparser                 2.20                       py_2    anaconda
pygments                  2.7.1                      py_0    anaconda
pyparsing                 2.4.7                      py_0    anaconda
pyqt                      5.9.2            py37h22d08a2_1    anaconda
pyrsistent                0.17.3           py37h7b6447c_0    anaconda
pytables                  3.6.1            py37h71ec239_0    anaconda
python                    3.7.9                h7579374_0    anaconda
python-dateutil           2.8.1                      py_0    anaconda
python-igraph             0.7.1.post7      py37h516909a_0    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2020.1                     py_0    anaconda
pyzmq                     19.0.2           py37he6710b0_1    anaconda
qt                        5.9.7                h5867ecd_1    anaconda
qtconsole                 4.7.7                      py_0    anaconda
qtpy                      1.9.0                      py_0    anaconda
readline                  8.0                  h7b6447c_0    anaconda
scanpy                    1.4.6                    pypi_0    pypi
scikit-learn              0.21.3           py37hd81dba3_0    anaconda
scipy                     1.3.2            py37h7c811a0_0    anaconda
seaborn                   0.11.0                     py_0    anaconda
send2trash                1.5.0                    py37_0    anaconda
setuptools                50.3.0           py37hb0f4dca_1    anaconda
setuptools-scm            6.0.1                    pypi_0    pypi
sip                       4.19.24          py37he6710b0_0    anaconda
six                       1.15.0                     py_0    anaconda
skorch                    0.7.0              pyh5ca1d4c_0    conda-forge
snappy                    1.1.8                he6710b0_0    anaconda
sortedcontainers          2.2.2                      py_0    anaconda
sqlite                    3.33.0               h62c20be_0    anaconda
statsmodels               0.10.1           py37hdd07704_0    anaconda
tabulate                  0.8.7                    py37_0    anaconda
tbb                       2020.3               hfd86e86_0    anaconda
tensorboard               2.0.0              pyhb38c66f_1    anaconda
terminado                 0.9.1                    py37_0    anaconda
testpath                  0.4.4                      py_0    anaconda
tk                        8.6.10               hbc83047_0    anaconda
torchvision               0.4.2                py37_cu101    pytorch
tornado                   6.0.4            py37h7b6447c_1    anaconda
tqdm                      4.50.2                     py_0    anaconda
traitlets                 5.0.5                      py_0    anaconda
ucsc-liftover             357                  h446ed27_4    bioconda
umap-learn                0.4.6            py37hc8dfbb8_0    conda-forge
wcwidth                   0.2.5                      py_0    anaconda
webencodings              0.5.1                    py37_1    anaconda
werkzeug                  1.0.1                      py_0    anaconda
wheel                     0.35.1                     py_0    anaconda
widgetsnbextension        3.5.1                    py37_0    anaconda
xlrd                      1.2.0                    pypi_0    pypi
xz                        5.2.5                h7b6447c_0    anaconda
zeromq                    4.3.3                he6710b0_3    anaconda
zipp                      3.3.1                      py_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.4.4                h0b5b093_3    anaconda
```

**Comment by wukevin** [comment]
During development, I sometimes saw the KeyError you're describing. It typically goes away if you run it again (I suspect there's some weird race condition somewhere inside AnnData that doesn't quite get updated consistently 100% of the time). I was just able to successfully run the command you described for SHAREseq. 

That said, there are some slight package mismatches that may exacerbate the issue:
* AnnData - you have 0.7.6 installed, the env yaml lists 0.6.22.
* ScanPy - you have 1.4.6 installed, can you try 1.4.4? That's the version I used 
* umap-learn - you have 0.4.6 installed. I just tested this version and it appears to have some odd conflicts with other package versions. Please try version 0.3.10 instead.

I have updated the environment.yml with the above scanpy and umap-learn versions, so if you could try creating a fresh environment with that, it could help narrow down the issue.

Thanks for testing this out and for the feedback.
