### ISSUE TITLE
Error when running on example data

### ISSUE THREAD

**Issue by boyinggong** [wukevin/babel#3]
Hi Kevin,

The BABEL model looks very interesting!

I was trying to run the model on one of the example datasets given in the `data/snareseq_GSE126074` folder. I created the `.h5` files from the data files provided. However, I encountered the following error when trying to train the model. It seems that the data was read in successfully, but an error occurred in later processing steps.

```bash
(babel) kinsley@kinsley-desktop:~/projects/clustering_project/multiomics_clustering/babel$ python bin/train_model.py --data data/snare/rna.h5 data/snare/atac.h5 --outdir mymodel
INFO:root:PyTorch CUDA version: 10.1.243
INFO:root:Parameter data: ['data/snare/rna.h5', 'data/snare/atac.h5']
INFO:root:Parameter snareseq: False
INFO:root:Parameter shareseq: None
INFO:root:Parameter linear: False
INFO:root:Parameter clustermethod: leiden
INFO:root:Parameter validcluster: 0
INFO:root:Parameter testcluster: 1
INFO:root:Parameter outdir: /home/kinsley/projects/clustering_project/multiomics_clustering/babel/mymodel
INFO:root:Parameter naive: False
INFO:root:Parameter hidden: [16]
INFO:root:Parameter pretrain: 
INFO:root:Parameter lossweight: [1.33]
INFO:root:Parameter optim: adam
INFO:root:Parameter lr: [0.01]
INFO:root:Parameter batchsize: [512]
INFO:root:Parameter earlystop: 25
INFO:root:Parameter seed: [182822]
INFO:root:Parameter device: 0
INFO:root:Parameter ext: pdf
INFO:root:Reading RNA data
INFO:root:Read in data/snare/rna.h5 for (10309, 33160) (obs x var)
INFO:root:Read in data/snare/atac.h5 for (10309, 244544) (obs x var)
Trying to set attribute `.obs` of view, making a copy.
Traceback (most recent call last):
  File "bin/train_model.py", line 554, in <module>
    main()
  File "bin/train_model.py", line 241, in main
    **rna_data_kwargs,
  File "/home/kinsley/projects/clustering_project/multiomics_clustering/babel/babel/sc_data_loaders.py", line 298, in __init__
    self.data_raw = reader(fname)
  File "/home/kinsley/projects/clustering_project/multiomics_clustering/babel/babel/utils.py", line 153, in sc_read_multi_files
    p.X = scipy.sparse.csr_matrix(p.X)
  File "/home/kinsley/anaconda3/envs/babel/lib/python3.7/site-packages/anndata/core/anndata.py", line 880, in X
    self._adata_ref._X[self._oidx, self._vidx] = value
  File "/home/kinsley/anaconda3/envs/babel/lib/python3.7/site-packages/scipy/sparse/_index.py", line 118, in __setitem__
    self._set_arrayXarray_sparse(i, j, x)
  File "/home/kinsley/anaconda3/envs/babel/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 805, in _set_arrayXarray_sparse
    self._zero_many(*self._swap((row, col)))
  File "/home/kinsley/anaconda3/envs/babel/lib/python3.7/site-packages/scipy/sparse/compressed.py", line 922, in _zero_many
    i, j, offsets)
ValueError: could not convert integer scalar
```

If it helps, here is how I created the `.h5` files in R. I am not sure if this is exactly required as input. BABEL seems like a really fun package, so it would be perfect if you could share your example input `.h5`  files in the data folder as well just to get people started. Thanks a lot!

```R
library(DropletUtils)
library(Matrix)

dat_dir = "data/snareseq_GSE126074/"
out_dir = "data/snare/"
if (!dir.exists(out_dir)){
  dir.create(out_dir)
}

rna_bc = read.table(
  file.path(dat_dir, "GSE126074_AdBrainCortex_SNAREseq_cDNA.barcodes.tsv"),
  stringsAsFactors = FALSE)$V1
rna_gene = read.table(
  file.path(dat_dir, "GSE126074_AdBrainCortex_SNAREseq_cDNA.genes.tsv"),
  stringsAsFactors = FALSE)$V1
rna_counts = readMM(
  file.path(dat_dir, "GSE126074_AdBrainCortex_SNAREseq_cDNA.counts.mtx"))
write10xCounts(file.path(out_dir, "rna.h5"), rna_counts, gene.id = rna_gene,
               gene.symbol = rna_gene, barcodes = rna_bc, version = '3')

atac_bc = read.table(
  file.path(dat_dir, "GSE126074_AdBrainCortex_SNAREseq_chromatin.barcodes.tsv"),
  stringsAsFactors = FALSE)$V1
atac_peak = read.table(
  file.path(dat_dir, "GSE126074_AdBrainCortex_SNAREseq_chromatin.peaks.tsv"),
  stringsAsFactors = FALSE)$V1
atac_counts = readMM(
  file.path(dat_dir, "GSE126074_AdBrainCortex_SNAREseq_chromatin.counts.mtx"))
write10xCounts(file.path(out_dir, "atac.h5"), atac_counts, gene.id = atac_peak,
               gene.symbol = atac_peak, barcodes = atac_bc, version = '3')
```

**Comment by wukevin** [comment]
I've never actually tried the process you're doing for SNAREseq (i.e. making the composite h5 files and feeding those in). The way the SNAREseq model is trained is using the following command line and resultant output:
```
❯ python ~/projects/commonspace/bin/train_model.py --snareseq --outdir snareseq --device 2
INFO:root:PyTorch CUDA version: 10.1.243
INFO:root:Parameter data: None
INFO:root:Parameter snareseq: True
INFO:root:Parameter shareseq: None
INFO:root:Parameter linear: False
INFO:root:Parameter clustermethod: leiden
INFO:root:Parameter validcluster: 0
INFO:root:Parameter testcluster: 1
INFO:root:Parameter outdir: /home/wukevin/projects/commonspace/snareseq
INFO:root:Parameter naive: False
INFO:root:Parameter hidden: [16]
INFO:root:Parameter pretrain:
INFO:root:Parameter lossweight: [1.33]
INFO:root:Parameter optim: adam
INFO:root:Parameter lr: [0.01]
INFO:root:Parameter batchsize: [512]
INFO:root:Parameter earlystop: 25
INFO:root:Parameter seed: [182822]
INFO:root:Parameter device: 2
INFO:root:Parameter ext: pdf
INFO:root:Reading RNA data
WARNING:root:Got multiple chromosomes for gene ACEA_U3: {'chr19', 'chr1', 'chr12', 'chr11'}, skipping
WARNING:root:Got multiple chromosomes for gene SCARNA4: {'chr1', 'chr11', 'chr5', 'chr2', 'chr3'}, skipping
WARNING:root:Got multiple chromosomes for gene SCARNA15: {'chr1', 'chr11', 'chr5', 'chr2', 'chr3'}, skipping
WARNING:root:Got multiple chromosomes for gene SNORA17: {'chr2', 'chr16', 'chr4'}, skipping
WARNING:root:Got multiple chromosomes for gene SNORA50: {'chr11', 'chr4'}, skipping
WARNING:root:Got multiple chromosomes for gene Vmn1r-ps5: {'chr6', 'chr5'}, skipping
WARNING:root:Got multiple chromosomes for gene SNORA43: {'chr9', 'chr12', 'chr8'}, skipping
WARNING:root:Got multiple chromosomes for gene SNORA76: {'chrX', 'chr8'}, skipping
WARNING:root:Got multiple chromosomes for gene U3: {'chr11', 'chr10'}, skipping
INFO:root:31499 genes with known positions
Trying to set attribute `.var` of view, making a copy.
Trying to set attribute `.obs` of view, making a copy.
INFO:root:Filtering 10309 cells
INFO:root:Remaining cells after min genes: 10302
INFO:root:Remaining cells after max genes: 10302
INFO:root:Filtering 29591 vars
INFO:root:Computing size factors
INFO:root:Log transforming data
INFO:root:Normalizing data to zero mean unit variance
INFO:root:Constructing leiden log clustered data split with valid test cluster {'0'} {'1'}
INFO:root:Setting size normalized counts
INFO:root:Setting log-normalized size-normalized counts
INFO:root:Created train data split with 7697 examples
INFO:root:Created valid data split with 1374 examples
INFO:root:Created test data split with 1231 examples
INFO:root:Aggregating ATAC clusters
Trying to set attribute `.X` of view, making a copy.
INFO:root:Filtering 10309 cells
INFO:root:Filtering 239241 vars
INFO:root:Remaining vars after min count: 223419
INFO:root:Remaining vars after min cells: 223419
INFO:root:Remaining vars after max cells: 215438
INFO:root:Got predefined split, ignoring mode
INFO:root:Created train data split with 7697 examples
INFO:root:Created valid data split with 1374 examples
INFO:root:Created test data split with 1231 examples
INFO:root:Checking obs names for two input datasets
INFO:root:Checking obs names for two input datasets
INFO:root:Checking obs names for two input datasets
INFO:root:Checking obs names for two input datasets
Trying to set attribute `.var` of view, making a copy.
... storing 'chrom' as categorical
INFO:root:ChromDecoder with 1 output activations
  epoch    train_loss    valid_loss    cp      dur
-------  ------------  ------------  ----  -------
      1        1.5395        0.5269     +  15.7498
      2        0.3661        0.3206     +  14.4334
      3        0.3212        0.3079     +  14.2213
      4        0.3105        0.3051     +  14.5191
...
```

As for h5 files, you can find the h5 files to train the human DM + HSR + PBMC model at the following link: https://office365stanford-my.sharepoint.com/:u:/g/personal/wukevin_stanford_edu/Edq1Cr6qejpOgzjZGa4bkvwB-LyH5MLbkLD6wGQCL4jvwA?e=T8IO54 (this is described under https://github.com/wukevin/babel#reproducing-pre-trained-model). These h5 files should be a good reference for the format required for crafting your own inputs.

Let me know if anything is unclear.

**Comment by wukevin** [comment]
I have also updated the README to include clearer instructions regarding both of your concerns. Thanks for the feedback!
