### ISSUE TITLE
Error when reproducing pre-trained model

### ISSUE THREAD

**Issue by yifnzhao** [wukevin/babel#6]
Hi,

Thanks for developing this tool! I encountered an error when trying to reproduce the pre-trained model.
The command I used was:
```python ../bin/train_model.py --data DM_rep4.h5 DM_rep8.h5 HSR_rep7.h5 HSR_rep8.h5 pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5 --outdir my_model```
And here is the error traceback:

```
Traceback (most recent call last):
  File "../bin/train_model.py", line 537, in <module>
    main()
  File "../bin/train_model.py", line 447, in main
    spliced_net.fit(sc_dual_train_dataset, y=None)
  File "/home/yiz188/.conda/envs/babel/lib/python3.7/site-packages/skorch/net.py", line 848, in fit
    self.partial_fit(X, y, **fit_params)
  File "/home/yiz188/.conda/envs/babel/lib/python3.7/site-packages/skorch/net.py", line 807, in partial_fit
    self.fit_loop(X, y, **fit_params)
  File "/home/yiz188/.conda/envs/babel/lib/python3.7/site-packages/skorch/net.py", line 735, in fit_loop
    for data in self.get_iterator(dataset_train, training=True):
  File "/home/yiz188/.conda/envs/babel/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/home/yiz188/.conda/envs/babel/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/home/yiz188/.conda/envs/babel/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
KeyError: Caught KeyError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/yiz188/.conda/envs/babel/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/yiz188/.conda/envs/babel/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/yiz188/.conda/envs/babel/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/n/data1/hms/dbmi/park/yifan/data/rnatac/babel-main/babel/sc_data_loaders.py", line 1023, in __getitem__
    x1 = self.dataset_x[i]
  File "/n/data1/hms/dbmi/park/yifan/data/rnatac/babel-main/babel/sc_data_loaders.py", line 842, in __getitem__
    return self.dset.get_item_data_split(index, self.split)
  File "/n/data1/hms/dbmi/park/yifan/data/rnatac/babel-main/babel/sc_data_loaders.py", line 671, in get_item_data_split
    return self.__getitem__(self.data_split_to_idx[split][idx])
  File "/n/data1/hms/dbmi/park/yifan/data/rnatac/babel-main/babel/sc_data_loaders.py", line 699, in __getitem__
    target = torch.from_numpy(self.size_norm_counts.var_vector(y_idx)).type(
  File "/home/yiz188/.local/lib/python3.7/site-packages/anndata/_core/anndata.py", line 1417, in var_vector
    return get_vector(self, k, "var", "obs", layer=layer)
  File "/home/yiz188/.local/lib/python3.7/site-packages/anndata/_core/index.py", line 180, in get_vector
    f"Could not find key {k} in .{idxdim}_names or .{coldim}.columns."
KeyError: 'Could not find key 29640 in .obs_names or .var.columns.'

```

**Comment by wukevin** [comment]
Can you post your full training log, as well as the output of `conda list`? I am not able to reproduce this issue, so I suspect that there is a mismatch in the underlying AnnData libraries.

**Comment by yifnzhao** [comment]
Hi thanks for looking into this!

Here's the training log:

```Parameter data: ['DM_rep4.h5', 'DM_rep8.h5', 'HSR_rep7.h5', 'HSR_rep8.h5', 'pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5']
Parameter snareseq: False
Parameter shareseq: None
Parameter nofilter: False
Parameter linear: False
Parameter clustermethod: leiden
Parameter validcluster: 0
Parameter testcluster: 1
Parameter outdir: /home/yiz188/babel-main/data2/my_model
Parameter naive: False
Parameter hidden: [16]
Parameter pretrain:
Parameter lossweight: [1.33]
Parameter optim: adam
Parameter lr: [0.01]
Parameter batchsize: [512]
Parameter earlystop: 25
Parameter seed: [182822]
Parameter device: 0
Parameter ext: pdf
Reading RNA data
Read in DM_rep4.h5 for (5517, 36601) (obs x var)
Read in DM_rep8.h5 for (5575, 36601) (obs x var)
Read in HSR_rep7.h5 for (6427, 36601) (obs x var)
Read in HSR_rep8.h5 for (6989, 36601) (obs x var)
Read in pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5 for (11909, 36601) (obs x var)
Got multiple chromosomes for gene DUS4L-BCAP29: {'7', '4'}, skipping
36144 genes with known positions
Filtering 36417 cells
Remaining cells after min genes: 36327
Remaining cells after max genes: 33268
Computing size factors
Found median counts of 10984.0
Found maximum counts of 49519.0
Log transforming data
Normalizing data to zero mean unit variance
Clipping to 0.5 percentile
Constructing leiden log clustered data split with valid test cluster {'0'} {'1'}
Setting size normalized counts
Setting log-normalized size-normalized counts
Created train data split with 29027 examples
Created valid data split with 2200 examples
Created test data split with 2041 examples
Aggregating ATAC clusters
Average/SD interval size after merging: 848.7149 2237.0747
Average/SD interval size after merging: 850.3778 2207.0694
Average/SD interval size after merging: 891.5949 2116.2663
Average/SD interval size after merging: 1005.6067 2175.7404
Aggregated 253646 bins
Got noncanonical chromsome in KI270728.1:232398-233036
Got noncanonical chromsome in KI270728.1:1453055-1453195
Got noncanonical chromsome in KI270728.1:1457822-1468143
Got noncanonical chromsome in KI270728.1:1468714-1472257
Got noncanonical chromsome in KI270728.1:1472949-1473574
Got noncanonical chromsome in KI270728.1:1704537-1705098
Got noncanonical chromsome in KI270728.1:1709206-1709349
Got noncanonical chromsome in KI270728.1:1714120-1714263
Got noncanonical chromsome in KI270728.1:1791204-1792542
Got noncanonical chromsome in KI270728.1:1803969-1804310
Got noncanonical chromsome in KI270728.1:1806112-1806314
Got noncanonical chromsome in KI270728.1:1806879-1811895
Got noncanonical chromsome in KI270728.1:1812870-1818077
Got noncanonical chromsome in KI270728.1:1806879-1811895
...
Got noncanonical chromsome in KI270713.1:37129-37638
Got noncanonical chromsome in KI270734.1:133761-134101
Got noncanonical chromsome in KI270731.1:4779-5134
Got noncanonical chromsome in KI270711.1:22863-23179
Got noncanonical chromsome in KI270726.1:27352-27794
Got noncanonical chromsome in KI270726.1:41529-42186
Read in DM_rep4.h5 for (5517, 253646) (obs x var)
Read in DM_rep8.h5 for (5575, 253646) (obs x var)
Read in HSR_rep7.h5 for (6427, 253646) (obs x var)
Read in HSR_rep8.h5 for (6989, 253646) (obs x var)
Read in pbmc_granulocyte_sorted_10k_filtered_feature_bc_matrix.h5 for (11909, 253646) (obs x var)
Filtering 245139 vars
Remaining vars after min count: 239922
Remaining vars after min cells: 239922
Remaining vars after max cells: 223897
Got predefined split, ignoring mode
Created train data split with 29027 examples
Created valid data split with 2200 examples
Created test data split with 2041 examples
Checking obs names for two input datasets
Checking obs names for two input datasets
Checking obs names for two input datasets
Checking obs names for two input datasets
ChromDecoder with 1 output activations
```

And the output of `conda list`:
```
# packages in environment at /home/yiz188/.conda/envs/babel:
#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                      1_llvm    conda-forge
absl-py                   0.10.0                   py37_0    anaconda
adjusttext                0.7.3.1                    py_1    conda-forge
anndata                   0.6.22.post1               py_0    bioconda
argon2-cffi               20.1.0           py37h7b6447c_1    anaconda
astropy                   4.0.1.post1      py37h8f50634_0    conda-forge
async_generator           1.10             py37h28b3542_0    anaconda
attrs                     20.2.0                     py_0    anaconda
backcall                  0.2.0                      py_0    anaconda
blas                      2.17                   openblas    conda-forge
bleach                    3.2.1                      py_0    anaconda
blosc                     1.19.0               hd408876_0    anaconda
brotlipy                  0.7.0           py37h7b6447c_1000    anaconda
bzip2                     1.0.8                h7b6447c_0    anaconda
c-ares                    1.16.1               h7b6447c_0    anaconda
ca-certificates           2020.10.14                    0    anaconda
cached-property           1.5.2                      py_0    anaconda
cairo                     1.14.12              h8948797_3    anaconda
captum                    0.2.0                         0    pytorch
certifi                   2020.6.20                py37_0    anaconda
cffi                      1.14.3           py37he30daa8_0    anaconda
chardet                   3.0.4                 py37_1003    anaconda
cryptography              3.1.1            py37h1ba5d50_0    anaconda
cudatoolkit               10.1.243             h6bb024c_0    anaconda
cycler                    0.10.0                   py37_0    anaconda
dbus                      1.13.18              hb2f20db_0    anaconda
decorator                 4.4.2                      py_0    anaconda
defusedxml                0.6.0                      py_0    anaconda
entrypoints               0.3                      py37_0    anaconda
expat                     2.2.10               he6710b0_2    anaconda
fast-histogram            0.9              py37heb32a55_0    anaconda
filelock                  3.0.12                     py_0    anaconda
fontconfig                2.13.1            hba837de_1005    conda-forge
freetype                  2.10.4               h5ab3b9f_0    anaconda
gdown                     4.0.2              pyhd8ed1ab_0    conda-forge
glib                      2.56.2               hd408876_0    anaconda
gmp                       6.1.2                hb3b607b_0    anaconda
graspy                    0.2                        py_0    conda-forge
grpcio                    1.31.0           py37hf8bcb03_0    anaconda
gst-plugins-base          1.14.0               hbbd80ab_1    anaconda
gstreamer                 1.14.0               hb453b48_1    anaconda
h5py                      2.10.0           py37h7918eee_0    anaconda
hdf5                      1.10.4               hb1b8bf9_0    anaconda
icu                       58.2                 he6710b0_3    anaconda
idna                      2.10                       py_0    anaconda
igraph                    0.7.1             h2166141_1005    conda-forge
importlib-metadata        2.0.0                      py_1    anaconda
importlib_metadata        2.0.0                         1    anaconda
intel-openmp              2020.2                      254    anaconda
intervaltree              3.0.2                      py_0    conda-forge
ipykernel                 5.3.4            py37h5ca1d4c_0    anaconda
ipython                   7.18.1           py37h5ca1d4c_0    anaconda
ipython_genutils          0.2.0                    py37_0    anaconda
ipywidgets                7.5.1                      py_1    anaconda
jedi                      0.17.2                   py37_0    anaconda
jinja2                    2.11.2                     py_0    anaconda
joblib                    0.17.0                     py_0    anaconda
jpeg                      9b                   habf39ab_1    anaconda
jsonschema                3.2.0                      py_2    anaconda
jupyter                   1.0.0            py37h89c1867_6    conda-forge
jupyter_client            6.1.7                      py_0    anaconda
jupyter_console           6.2.0                      py_0    anaconda
jupyter_core              4.6.3                    py37_0    anaconda
jupyterlab_pygments       0.1.2                      py_0    anaconda
kiwisolver                1.2.0            py37hfd86e86_0    anaconda
lcms2                     2.11                 h396b838_0    anaconda
ld_impl_linux-64          2.33.1               h53a641e_7    anaconda
leidenalg                 0.7.0            py37h3340039_2    conda-forge
libblas                   3.8.0               17_openblas    conda-forge
libcblas                  3.8.0               17_openblas    conda-forge
libedit                   3.1.20191231         h14c3975_1    anaconda
libffi                    3.3                  he6710b0_2    anaconda
libgcc-ng                 11.2.0              h1d223b6_11    conda-forge
libgfortran-ng            7.3.0                hdf63c60_0    anaconda
libiconv                  1.15                 h63c8f33_5    anaconda
liblapack                 3.8.0               17_openblas    conda-forge
liblapacke                3.8.0               17_openblas    conda-forge
libllvm10                 10.0.1               hbcb73fb_5    anaconda
libopenblas               0.3.10               h5a2b251_0    anaconda
libpng                    1.6.37               hbc83047_0    anaconda
libprotobuf               3.13.0.1             hd408876_0    anaconda
libsodium                 1.0.18               h7b6447c_0    anaconda
libstdcxx-ng              11.2.0              he4da1e4_11    conda-forge
libtiff                   4.1.0                h2733197_1    anaconda
libuuid                   2.32.1            h7f98852_1000    conda-forge
libxcb                    1.14                 h7b6447c_0    anaconda
libxml2                   2.9.10               hb55368b_3    anaconda
llvm-openmp               12.0.1               h4bd325d_1    conda-forge
llvmlite                  0.34.0           py37h269e1b5_4    anaconda
louvain                   0.6.1            py37he1b5a44_2    conda-forge
lz4-c                     1.9.2                heb0550a_3    anaconda
lzo                       2.10                 h7b6447c_2    anaconda
markdown                  3.3.2                    py37_0    anaconda
markupsafe                1.1.1            py37h14c3975_1    anaconda
matplotlib                3.3.1                         0    anaconda
matplotlib-base           3.3.1            py37h817c723_0    anaconda
mistune                   0.8.4           py37h14c3975_1001    anaconda
mkl                       2020.2                      256    anaconda
mock                      4.0.2                      py_0    anaconda
mpl-scatter-density       0.7                        py_0    conda-forge
multicore-tsne            0.1_d4ff4aab     py37hda21425_1    conda-forge
mvlearn                   0.4.0              pyhd8ed1ab_0    conda-forge
mysql-connector-c         6.1.11               h597af5e_1    anaconda
natsort                   7.0.1                      py_0    anaconda
nbclient                  0.5.1                      py_0    anaconda
nbconvert                 6.0.7                    py37_0    anaconda
nbformat                  5.0.8                      py_0    anaconda
ncurses                   6.2                  he6710b0_1    anaconda
nest-asyncio              1.4.1                      py_0    anaconda
networkx                  2.5                        py_0    anaconda
ninja                     1.10.1           py37hfd86e86_0    anaconda
notebook                  6.1.4                    py37_0    anaconda
numba                     0.51.2           py37h04863e7_1    anaconda
numexpr                   2.7.1            py37h7ea95a0_0    anaconda
numpy                     1.17.5           py37haa41c4c_1    conda-forge
olefile                   0.46                     py37_0    anaconda
openssl                   1.1.1h               h7b6447c_0    anaconda
packaging                 20.4                       py_0    anaconda
pandas                    0.25.3           py37he6710b0_0    anaconda
pandoc                    2.11                 hb0f4dca_0    anaconda
pandocfilters             1.4.2                    py37_1    anaconda
parso                     0.7.0                      py_0    anaconda
patsy                     0.5.1                    py37_0    anaconda
pcre                      8.44                 he6710b0_0    anaconda
pexpect                   4.8.0                    py37_1    anaconda
pickleshare               0.7.5                 py37_1001    anaconda
pillow                    8.0.0            py37h9a89aac_0    anaconda
pip                       20.2.4                   py37_0    anaconda
pixman                    0.40.0               h7b6447c_0    anaconda
prometheus_client         0.8.0                      py_0    anaconda
prompt-toolkit            3.0.8                      py_0    anaconda
prompt_toolkit            3.0.8                         0    anaconda
protobuf                  3.13.0.1         py37he6710b0_1    anaconda
ptyprocess                0.6.0                    py37_0    anaconda
pycairo                   1.19.1           py37h2a1e443_0    anaconda
pycparser                 2.20                       py_2    anaconda
pygments                  2.7.1                      py_0    anaconda
pyopenssl                 19.1.0                     py_1    anaconda
pyparsing                 2.4.7                      py_0    anaconda
pyqt                      5.9.2            py37h22d08a2_1    anaconda
pyrsistent                0.17.3           py37h7b6447c_0    anaconda
pysocks                   1.7.1                    py37_1    anaconda
pytables                  3.6.1            py37h71ec239_0    anaconda
python                    3.7.9                h7579374_0    anaconda
python-dateutil           2.8.1                      py_0    anaconda
python-igraph             0.7.1.post7      py37h516909a_0    conda-forge
python-picard             0.4                pyh5ca1d4c_1    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pytorch                   1.3.1           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pytz                      2020.1                     py_0    anaconda
pyzmq                     19.0.2           py37he6710b0_1    anaconda
qt                        5.9.7                h5867ecd_1    anaconda
qtconsole                 4.7.7                      py_0    anaconda
qtpy                      1.9.0                      py_0    anaconda
readline                  8.0                  h7b6447c_0    anaconda
requests                  2.24.0                     py_0    anaconda
scanpy                    1.4.4.post1                py_0    bioconda
scikit-learn              0.21.3           py37h22eb022_0    anaconda
scipy                     1.3.2            py37he2b7bc3_0    anaconda
seaborn                   0.11.0                     py_0    anaconda
send2trash                1.5.0                    py37_0    anaconda
setuptools                50.3.0           py37hb0f4dca_1    anaconda
sip                       4.19.24          py37he6710b0_0    anaconda
six                       1.15.0                     py_0    anaconda
skorch                    0.7.0              pyh5ca1d4c_0    conda-forge
snappy                    1.1.8                he6710b0_0    anaconda
sortedcontainers          2.2.2                      py_0    anaconda
sqlite                    3.33.0               h62c20be_0    anaconda
statsmodels               0.10.1           py37hdd07704_0    anaconda
tabulate                  0.8.7                    py37_0    anaconda
tensorboard               2.0.0              pyhb38c66f_1    anaconda
terminado                 0.9.1                    py37_0    anaconda
testpath                  0.4.4                      py_0    anaconda
tk                        8.6.10               hbc83047_0    anaconda
torchvision               0.4.2                py37_cu101    pytorch
tornado                   6.0.4            py37h7b6447c_1    anaconda
tqdm                      4.50.2                     py_0    anaconda
traitlets                 5.0.5                      py_0    anaconda
typing_extensions         3.10.0.2           pyha770c72_0    conda-forge
ucsc-liftover             357                  h446ed27_4    bioconda
umap-learn                0.3.10                   py37_1    conda-forge
urllib3                   1.25.11                    py_0    anaconda
wcwidth                   0.2.5                      py_0    anaconda
webencodings              0.5.1                    py37_1    anaconda
werkzeug                  1.0.1                      py_0    anaconda
wheel                     0.35.1                     py_0    anaconda
widgetsnbextension        3.5.1                    py37_0    anaconda
xz                        5.2.5                h7b6447c_0    anaconda
zeromq                    4.3.3                he6710b0_3    anaconda
zipp                      3.3.1                      py_0    anaconda
zlib                      1.2.11               h7b6447c_3    anaconda
zstd                      1.4.4                h0b5b093_3    anaconda
```

**Comment by wukevin** [comment]
Can you try the following:

1. Remove your current `babel` environment using `conda remove --name babel --all`
2. Re-create the babel environment using the attached yaml file
[environment2.txt](https://github.com/wukevin/babel/files/7577831/environment2.txt)
3. Try re-running the training command?

**Comment by yifnzhao** [comment]
It works now, thanks! Sorry about the late reply.

**Comment by sannalda** [comment]
Hi! I've had the same problem and am trying to use the new environment file, but I think its a bit outdated (there are package conflicts). I was wondering if you had an updated environment?
